#ifndef IR_CONFIG_H
#define IR_CONFIG_H

#include <stdint.h>

#define IR_BUILD_PROFILE_DEVELOPMENT  (1U)
#define IR_BUILD_PROFILE_RELEASE      (2U)

#ifndef IR_BUILD_PROFILE
#define IR_BUILD_PROFILE IR_BUILD_PROFILE_RELEASE
#endif

#if (IR_BUILD_PROFILE == IR_BUILD_PROFILE_DEVELOPMENT)
#define IR_ENABLE_CONTINUOUS_SD_TRACE (1U)
#elif (IR_BUILD_PROFILE == IR_BUILD_PROFILE_RELEASE)
#define IR_ENABLE_CONTINUOUS_SD_TRACE (0U)
#else
#error "Invalid IR_BUILD_PROFILE"
#endif

#ifndef IR_ENABLE
#define IR_ENABLE (1U)
#endif

#ifndef IR_ENABLE_PERSISTENCE
#define IR_ENABLE_PERSISTENCE (1U)
#endif

#ifndef IR_ENABLE_EXPORT
#define IR_ENABLE_EXPORT (1U)
#endif

#ifndef IR_RETAINED_RAM_BYTES
#define IR_RETAINED_RAM_BYTES (10U * 1024U)
#endif

#ifndef IR_RETAINED_RESERVED_BYTES
#define IR_RETAINED_RESERVED_BYTES (128U)
#endif

#ifndef IR_BUILD_ID
#define IR_BUILD_ID (0x01000002UL)
#endif

#ifndef IR_SCHEMA_VERSION
#define IR_SCHEMA_VERSION (0x0102U)
#endif

#ifndef IR_DEV_TRACE_QUEUE_RECORDS
#define IR_DEV_TRACE_QUEUE_RECORDS (32U)
#endif

#ifndef IR_SERVICE_TRACE_BUDGET
#define IR_SERVICE_TRACE_BUDGET (8U)
#endif

#endif /* IR_CONFIG_H */
